version: '3.8'

services:

  # Golang Service
  golang-service:
    build:
      context: ./golang-service
      dockerfile: Dockerfile
    container_name: golang-service
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://neondb_owner:npg_RCKnZ94HUIzV@ep-round-bar-a1pyj7b4-pooler.ap-southeast-1.aws.neon.tech/hack-the-ai?sslmode=require&channel_binding=require
      - SERVER_PORT=8080
    networks:
      - saracen-network
    volumes:
      - ./golang-service:/app
    restart: unless-stopped

  # Node.js Service
  node-service:
    build:
      context: ./nodejs-service
      dockerfile: Dockerfile
    container_name: nodejs-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOLANG_API_URL=http://golang-service:8080
      - DATABASE_URL=postgresql://neondb_owner:npg_RCKnZ94HUIzV@ep-round-bar-a1pyj7b4-pooler.ap-southeast-1.aws.neon.tech/hack-the-ai?sslmode=require&channel_binding=require
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - golang-service
    networks:
      - saracen-network
    restart: unless-stopped

networks:
  saracen-network:
    driver: bridge
