version: '3.8'

services:

  # Golang Service
  golang-service:
    build:
      context: ./golang-service
      dockerfile: Dockerfile
    container_name: saracen-go-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=saracen_voting
      - DB_USER=saracen_user
      - DB_PASSWORD=saracen_pass
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - saracen-network
    volumes:
      - ./golang-service:/app
    restart: unless-stopped

  # Node.js Service
  node-service:
    build: .
    container_name: hack-the-ai
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_RCKnZ94HUIzV@ep-round-bar-a1pyj7b4-pooler.ap-southeast-1.aws.neon.tech/hack-the-ai?sslmode=require&channel_binding=require"
      PORT: 8000
    volumes:
      - .:/app
      - /app/node_modules

networks:
  saracen-network:
    driver: bridge