services:
  node-service:
    build: .
    container_name: hack-the-ai
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_RCKnZ94HUIzV@ep-round-bar-a1pyj7b4-pooler.ap-southeast-1.aws.neon.tech/hack-the-ai?sslmode=require&channel_binding=require"
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules
